// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlu_EHO5HcXB9dcVKcn8aPxuqZt57BkwI',
    appId: '1:297204080232:web:e3423f1159878d332d25dd',
    messagingSenderId: '297204080232',
    projectId: 'miniprogram-3b8ce',
    authDomain: 'miniprogram-3b8ce.firebaseapp.com',
    storageBucket: 'miniprogram-3b8ce.appspot.com',
    measurementId: 'G-6PPMGGXV34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-uIYPFUSyyGNUUIBI_XwE7ku2AjEepnY',
    appId: '1:297204080232:android:c0c16e4b47f6e20e2d25dd',
    messagingSenderId: '297204080232',
    projectId: 'miniprogram-3b8ce',
    storageBucket: 'miniprogram-3b8ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATZ5F0g6G5psO3ryiqUD3JMh2EwCZj32Y',
    appId: '1:297204080232:ios:87fd870c358abb6c2d25dd',
    messagingSenderId: '297204080232',
    projectId: 'miniprogram-3b8ce',
    storageBucket: 'miniprogram-3b8ce.appspot.com',
    iosBundleId: 'com.example.flutterFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATZ5F0g6G5psO3ryiqUD3JMh2EwCZj32Y',
    appId: '1:297204080232:ios:87fd870c358abb6c2d25dd',
    messagingSenderId: '297204080232',
    projectId: 'miniprogram-3b8ce',
    storageBucket: 'miniprogram-3b8ce.appspot.com',
    iosBundleId: 'com.example.flutterFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlu_EHO5HcXB9dcVKcn8aPxuqZt57BkwI',
    appId: '1:297204080232:web:ac9155dda5c56c552d25dd',
    messagingSenderId: '297204080232',
    projectId: 'miniprogram-3b8ce',
    authDomain: 'miniprogram-3b8ce.firebaseapp.com',
    storageBucket: 'miniprogram-3b8ce.appspot.com',
    measurementId: 'G-9BXDMTY6GG',
  );
}
